name: Fetch and process job listings

on:
  schedule:
    - cron: '0 12 * * *' # at 5 am PST each day.
  workflow_dispatch:

jobs:
  run_notebook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas tqdm numpy requests beautifulsoup4 sqlalchemy
      - name: Run script
        run: python 00-fetch-listings.py
      - name: Commit and push if there are changes
        run: |
          git config --global user.email "mattstiles@gmail.com"
          git config --global user.name "Matt Stiles"
          git add .
          git commit -m "Updated job listings" || echo "No changes to commit"
          git remote set-url origin https://${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/stiles/jobs.git
          git push
      - name: Send notification email
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: You fetched new Netflix job listings!
          to: haekeostiles@gmail.com
          from: GitHub Actions
          body: email_content
